version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: react.dockerfile
    ports:
      - "27017:27017"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: express.dockerfile
    ports:
      - "3000:3000"


volumes:
  mongo-data:
