version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: express.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_IP=${DB_IP}
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: mongodb.dockerfile
    env_file:
      - .env 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
